name: GraphQL - repos

on: 
  workflow_dispatch:

jobs:
  graphql:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: GraphQL data scrape
    outputs:
      output1: ${{ steps.repos.outputs.data }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3    
      - name: Org repos
        id: repos
        uses: dfberry/gh-action-graphql@v1.8
        with:
          github_personal_access_token: ${{ secrets.PAT }}
          query_type: 'org_repos'
      - name: Create file
        run: |
          cat <<EOF > repos.json
          ${{ steps.repos.outputs.data }}
      - name: List files
        id: list_files
        run: |
            pwd && ls -la 
