name: TYPESCRIPT action test

on: 
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: TYPESCRIPT action test
    steps:
      - name: GraphQL action step - fails without minimum var - PAT
        id: test1e
        uses: diberry/typescript-action@v1.2
        with:
          github-personal-access-token: ${{ secrets.PAT }}
      # Use the output from the `hello` step
      - name: Get the data
        run: echo "The error was ${{ steps.test1e.outputs.data }}"I t