name: TYPESCRIPT action test

on: 
  workflow_dispatch:

jobs:
  graphql:
    runs-on: ubuntu-latest
    name: GraphQL data scrape
    steps:
      - name: Who Am I
        id: whoami
        uses: dfberry/gh-action-graphql@v1.2
        with:
          github_personal_access_token: ${{ secrets.PAT }}
          query_type: 'whoami'
      # Use the output from the `hello` step
      - name: Get the data
        run: echo "The output was ${{ steps.whoami.data }}"
