name: TYPESCRIPT action test

on: 
  workflow_dispatch:

jobs:
  graphql:
    runs-on: ubuntu-latest
    name: GraphQL data scrape
    outputs:
      output1: ${{ steps.whoami.outputs.data }}
    steps:
      - name: Who Am I
        id: whoami
        uses: dfberry/gh-action-graphql@v1.5
        with:
          github_personal_access_token: ${{ secrets.PAT }}
          query_type: 'whoami'
      # Use the output from the `hello` step
      - name: Who Am I result
        id: whoami-getdata
        run: echo "The output was ${{ steps.whoami.outputs.data }}"
