name: GraphQL query action

on: 
  workflow_dispatch:

jobs:
  graphql:
    runs-on: ubuntu-latest
    name: GraphQL data scrape
    outputs:
      output1: ${{ steps.whoami.outputs.data }}
    steps:
      - name: Who Am I
        id: whoami
        uses: dfberry/gh-action-graphql@v1.5
        with:
          github_personal_access_token: ${{ secrets.PAT }}
          query_type: 'whoami'
      - name: Who Am I result
        id: whoami-getdata
        run: echo "The output was ${{ steps.whoami.outputs.data }}"
      - name: Azure-Samples repos
        id: azure_samples_repos
        uses: dfberry/gh-action-graphql@v1.5
        with:
          github_personal_access_token: ${{ secrets.PAT }}
          query_type: 'org_repos'
      - name: Azure-Samples repos result
        id: azure_samples_repos_getdata
        run: echo "The output was ${{ steps.azure_samples_repos.outputs.data }}"
