name: GraphQL - who am i

on: 
  workflow_dispatch:

jobs:
  graphql:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: GraphQL data scrape
    outputs:
      output1: ${{ steps.whoami.outputs.data }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3    
      - name: Who Am I
        id: whoami
        uses: dfberry/gh-action-graphql@v1.6
        with:
          github_personal_access_token: ${{ secrets.PAT }}
          query_type: 'whoami'
      - name: List files
        id: list_files
        run: |
            sudo cat ${{ steps.whoami.outputs.data }} >> whoami.data.json && pwd && ls -la 
      - name: Create 3rd file
        run: |
          cat <<EOF > $HOME/whoami.data3.json
          ${{ steps.whoami.outputs.data }}
          EOF            
      - name: Write File
        uses: DamianReeves/write-file-action@v1.2
        with:
          path: ${{ env.home}}/whoami.data2.json  
          contents: |
            ${{ steps.whoami.outputs.data }}
          write-mode: overwrite           
      - name: Upload archive - who am i
        uses: actions/upload-artifact@v3
        with:
          name: Upload whoami data file
          path: ${{ env.home}}/whoami.data.json  
          retention-days: 5
      - name: Upload archive - who am i 2
        uses: actions/upload-artifact@v3
        with:
          name: Upload whoami data file
          path: ${{ env.home}}/whoami.data2.json  
          retention-days: 5          
