name: GraphQL - who am i

on: 
  workflow_dispatch:

jobs:
  graphql:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: GraphQL data scrape
    outputs:
      output1: ${{ steps.whoami.outputs.data }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3    
      - name: Who Am I
        id: whoami
        uses: dfberry/gh-action-graphql@v1.8
        with:
          github_personal_access_token: ${{ secrets.PAT }}
          query_type: 'whoami'
      - name: Create 3rd file
        run: |
          cat <<EOF > ${{ github_workspace }}/whoami.data3.json
          ${{ steps.whoami.outputs.data }}
      - name: Show file contents
        id: show_file_contents
        run: |
            cat ${{ github_workspace }}/whoami.data3.json          
      - name: List files
        id: list_files
        run: |
            pwd && ls -la 
      - name: Git status
        id: git_status
        run: |
            git_status             
      - name: Upload file to repository
        run: |
          git config --global user.name "dfberry"
          git config --global user.email "dinaberry@outlook.com"
          git add ${{ github_workspace }}/whoami.data3.json
          git commit -m "graphql data"
          git push
