name: GitHub action - write file

on: 
  workflow_dispatch:

jobs:
  data_as_file:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: GraphQL data scrape
    outputs:
      output1: ${{ steps.whoami.outputs.data }}
    steps:
    
    - name: Checkout repo
      uses: actions/checkout@v3   
      
    - name: DamianReeves example
      uses: DamianReeves/write-file-action@v1.2
      with:
        path: ./test_hello_world_damianreeves
        contents: |
          Hello World!
        write-mode: append

    - name: List files
      id: list_files
      run: |
          pwd && ls -la 
