name: GitHub action - write file

on: 
  workflow_dispatch:

jobs:
  data_as_file:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: GraphQL data scrape
    outputs:
      output1: ${{ steps.whoami.outputs.data }}
    steps:
    
    - name: Checkout repo
      uses: actions/checkout@v3   
      
    - name: Get current time
      uses: josStorer/get-current-time@v2.0.2
      id: current-time
      with:
        format: YYYYMMDD-HH
        utcOffset: "+08:00"
    - name: Use current time
      env:
        TIME: "${{ steps.current-time.outputs.time }}"
        R_TIME: "${{ steps.current-time.outputs.readableTime }}"
        F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
        YEAR: "${{ steps.current-time.outputs.year }}"
        DAY: "${{ steps.current-time.outputs.day }}"
      run: echo $TIME $R_TIME $F_TIME $YEAR $DAY

    - name: DamianReeves example
      uses: DamianReeves/write-file-action@v1.2
      with:
        path: ./test_hello_world_damianreeves_${{ steps.current-time.outputs.formattedTime }}
        contents: |
          Hello World!
        write-mode: append

    - name: List files
      id: list_files
      run: |
          echo "{environment_variable_name}={value}" >> $GITHUB_ENV

    - name: Commit new file(s) to repo
      uses: EndBug/add-and-commit@v9
      with:
        author_name: Dina Berry
        author_email: dinaberry@outlook.com
        message: 'Committing files {env.date}'

    - name: Get datetime
      id: getdatetime
      run: |
          echo "{env.date}" 

    - name: Set the value
      id: step_one
      run: |
        echo "action_state=yellow" >> $GITHUB_ENV
    - name: Use the value
      id: step_two
      run: |
        echo "${{ env.action_state }}" # This will output 'yellow'